name: Despliegue de Infraestructura (Dev)

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite correr el pipeline manualmente si lo necesitas

jobs:
  deploy:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/environments/dev

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Instalar Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve